version: '3.8'

services:
  app:
    image: node:16.17.1
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=development
    command: >
      bash -c "npm install --legacy-peer-deps &&
               npm run build-dev"

volumes:
  node_modules:
